name = "Creathions Client"
author = "AeronSor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ca758dac0860eaf07f163d9b40eb2b4a0daf6ec63ef6075ee3fab9383f38260"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"
