name = "Creathions"
author = "AeronSor"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3cc48d8c5bee9ef7776870a12259c433a40802c2d08f0ef69e9c50cbb9605d25"

[versions]
forge = "40.2.4"
minecraft = "1.18.2"

[options]
datapack-folder = "paxi"
